___

<a href='http://www.pieriandata.com'> <img src='../../Pierian_Data_Logo.png' /></a>
___

# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [1]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [2]:
salaries_csv = pd.read_csv('Salaries.csv')

In [7]:
salaries_csv.head(4)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN

** Check the head of the DataFrame. **

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [4]:
salaries_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [8]:
salaries_csv['BasePay'].mean()

66325.44884050643

** What is the highest amount of OvertimePay in the dataset ? **

In [9]:
salaries_csv['OvertimePay'].max()

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [16]:
name = 'JOSEPH DRISCOLL'
salaries_csv[salaries_csv['EmployeeName'].str.contains(name)]['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [17]:
salaries_csv[salaries_csv['EmployeeName'].str.contains(name)]['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [24]:
salaries_csv.iloc[salaries_csv['TotalPayBenefits'].idxmax()]['EmployeeName']

'NATHANIEL FORD'

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [25]:
salaries_csv.iloc[salaries_csv['TotalPayBenefits'].idxmin()]['EmployeeName']

'Joe Lopez'

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [31]:
salaries_csv.groupby('Year')['Year'].mean()

Year
2011    2011
2012    2012
2013    2013
2014    2014
Name: Year, dtype: int64

** How many unique job titles are there? **

In [48]:
jobs_grouped = salaries_csv.groupby('JobTitle')['JobTitle']
jobs_grouped.ngroups

2159

** What are the top 5 most common jobs? **

In [57]:
salaries_csv.groupby('JobTitle').count()

,Id,EmployeeName,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
JobTitle,,,,,,,,,,,,
ACCOUNT CLERK,83,83,83,83,83,0,83,83,83,0,83,0
ACCOUNTANT,5,5,5,5,5,0,5,5,5,0,5,0
ACCOUNTANT INTERN,48,48,48,48,48,0,48,48,48,0,48,0
"ACPO,JuvP, Juv Prob (SFERS)",1,1,1,1,1,1,1,1,1,0,1,0
ACUPUNCTURIST,1,1,1,1,1,0,1,1,1,0,1,0
ADMINISTRATIVE ANALYST,93,93,93,93,93,0,93,93,93,0,93,0
ADMINISTRATIVE ANALYST II,2,2,2,2,2,0,2,2,2,0,2,0
ADMINISTRATIVE ANALYST III,2,2,2,2,2,0,2,2,2,0,2,0
ADMINISTRATIVE ENGINEER,10,10,10,10,10,0,10,10,10,0,10,0
ADMINISTRATIVE SERVICES MANAGER,3,3,3,3,3,0,3,3,3,0,3,0
"ADMINISTRATOR, SFGH MEDICAL CENTER",1,1,1,1,1,0,1,1,1,0,1,0
AFFIRMATIVE ACTION SPECIALIST,6,6,6,6,6,0,6,6,6,0,6,0
AGRICULTURAL INSPECTOR,2,2,2,2,2,0,2,2,2,0,2,0
"AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS ADMINI",1,1,1,1,1,0,1,1,1,0,1,0
"AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS",1,1,1,1,1,0,1,1,1,0,1,0
AIRPORT COMMUNICATIONS OPERATOR,27,27,27,27,27,0,27,27,27,0,27,0
AIRPORT COMMUNICATIONS SUPERVISOR,2,2,2,2,2,0,2,2,2,0,2,0
AIRPORT ECONOMIC PLANNER,13,13,13,13,13,0,13,13,13,0,13,0
AIRPORT ELECTRICIAN,17,17,17,17,17,0,17,17,17,0,17,0
AIRPORT ELECTRICIAN SUPERVISOR,2,2,2,2,2,0,2,2,2,0,2,0
AIRPORT EMERGENCY PLANNING COORDINATOR,2,2,2,2,2,0,2,2,2,0,2,0
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR,1,1,1,1,1,0,1,1,1,0,1,0
AIRPORT NOISE ABATEMENT SPECIALIST,2,2,2,2,2,0,2,2,2,0,2,0
AIRPORT OPERATIONS SUPERVISOR,12,12,12,12,12,0,12,12,12,0,12,0
AIRPORT POLICE SERVICES AIDE,187,187,187,187,187,0,187,187,187,0,187,0
AIRPORT PROPERTY SPECIALIST I,13,13,13,13,13,0,13,13,13,0,13,0
AIRPORT SAFETY OFFICER,40,40,40,40,40,0,40,40,40,0,40,0
ANESTHETIST,25,25,25,25,25,0,25,25,25,0,25,0
ANIMAL CARE ASSISTANT SUPERVISOR,1,1,1,1,1,0,1,1,1,0,1,0
ANIMAL CARE ATTENDANT,14,14,14,14,14,0,14,14,14,0,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...
Wastewater Control Inspector,26,26,25,26,26,26,26,26,26,0,26,0
Water & Power Maint Sprv 1,9,9,9,9,9,9,9,9,9,0,9,0
Water Conservation Admin,12,12,12,12,12,12,12,12,12,0,12,0
Water Const&Main Supt,5,5,5,5,5,5,5,5,5,0,5,0
Water Meter Repairer,18,18,18,18,18,18,18,18,18,0,18,0
Water Meter Shop Supervisor 1,2,2,2,2,2,2,2,2,2,0,2,0
Water Operations Analyst,35,35,35,35,35,35,35,35,35,0,35,0
Water Quality Tech III,24,24,24,24,24,24,24,24,24,0,24,0
Water Quality Technician,32,32,32,32,32,32,32,32,32,0,32,0
Water QualityTech I/II,69,69,66,69,69,69,69,69,69,0,69,0
Water Service Inspector,82,82,82,82,82,82,82,82,82,0,82,0
Watershed Forester,6,6,6,6,6,6,6,6,6,0,6,0
Watershed Keeper,76,76,76,76,76,76,76,76,76,0,76,0
Watershed Keeper Supervisor,8,8,8,8,8,8,8,8,8,0,8,0
Watershed Worker (Seasonal),86,86,86,86,86,86,86,86,86,0,86,0
Welder,38,38,38,38,38,38,38,38,38,0,38,0
Welfare Fraud Investigator,16,16,16,16,16,16,16,16,16,0,16,0
Wharfinger 1,3,3,3,3,3,3,3,3,3,0,3,0
Wharfinger 2,10,10,10,10,10,10,10,10,10,0,10,0
Window Cleaner,50,50,50,50,50,50,50,50,50,0,50,0
Window Cleaner Supervisor,3,3,3,3,3,3,3,3,3,0,3,0
Wire Rope Cable Maint Mechanic,30,30,29,30,30,30,30,30,30,0,30,0
Wire Rope Cable Maint Sprv,3,3,3,3,3,3,3,3,3,0,3,0
Worker's Comp Supervisor 1,14,14,14,14,14,14,14,14,14,0,14,0
Worker's Compensation Adjuster,74,74,74,74,74,74,74,74,74,0,74,0
X-RAY LABORATORY AIDE,26,26,26,26,26,0,26,26,26,0,26,0
X-Ray Laboratory Aide,100,100,100,100,100,100,100,100,100,0,100,0
"YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS",1,1,1,1,1,0,1,1,1,0,1,0
Youth Comm Advisor,4,4,4,4,4,4,4,4,4,0,4,0
ZOO CURATOR,1,1,1,1,1,0,1,1,1,0,1,0

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148635,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148645,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148653,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [59]:
salaries_csv[salaries_csv['EmployeeName'].str.contains('Chief')]

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

477

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!